# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthorizationForm(object):
    def setupUi(self, AuthorizationForm):
        AuthorizationForm.setObjectName("AuthorizationForm")
        AuthorizationForm.resize(632, 405)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AuthorizationForm.sizePolicy().hasHeightForWidth())
        AuthorizationForm.setSizePolicy(sizePolicy)
        AuthorizationForm.setMaximumSize(QtCore.QSize(16777215, 16777215))
        AuthorizationForm.setFocusPolicy(QtCore.Qt.ClickFocus)
        AuthorizationForm.setStyleSheet("QWidget {\n"
"    background-color: rgb(36, 36, 36);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(AuthorizationForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(AuthorizationForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(600, 200))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/SMTP_logo_wo_subtext-1280x231.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setIndent(2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.login_line = QtWidgets.QLineEdit(AuthorizationForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_line.sizePolicy().hasHeightForWidth())
        self.login_line.setSizePolicy(sizePolicy)
        self.login_line.setMinimumSize(QtCore.QSize(261, 41))
        self.login_line.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.login_line.setFont(font)
        self.login_line.setStyleSheet("QLineEdit { \n"
"    border: 2px solid rgb(30, 30, 30);\n"
"    border-radius: 20px; \n"
"    color: #FFF; \n"
"    background-color: rgb(62, 62, 62); \n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"} \n"
"\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(75, 75, 75);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(102, 102, 102);\n"
"    border-color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"")
        self.login_line.setAlignment(QtCore.Qt.AlignCenter)
        self.login_line.setObjectName("login_line")
        self.verticalLayout.addWidget(self.login_line)
        self.password_line = QtWidgets.QLineEdit(AuthorizationForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_line.sizePolicy().hasHeightForWidth())
        self.password_line.setSizePolicy(sizePolicy)
        self.password_line.setMinimumSize(QtCore.QSize(261, 41))
        self.password_line.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.password_line.setFont(font)
        self.password_line.setStyleSheet("QLineEdit { \n"
"    border: 2px solid rgb(30, 30, 30);\n"
"    border-radius: 20px; \n"
"    color: #FFF; \n"
"    background-color: rgb(62, 62, 62); \n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"} \n"
"\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(75, 75, 75);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(102, 102, 102);\n"
"    border-color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"")
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setAlignment(QtCore.Qt.AlignCenter)
        self.password_line.setObjectName("password_line")
        self.verticalLayout.addWidget(self.password_line)
        self.logIn_button = QtWidgets.QPushButton(AuthorizationForm)
        self.logIn_button.setMinimumSize(QtCore.QSize(211, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.logIn_button.setFont(font)
        self.logIn_button.setStyleSheet("QPushButton { \n"
"    border: 2px solid rgb(30, 30, 30);\n"
"    border-radius: 20px; \n"
"    color: #FFF; \n"
"    background-color: rgb(62, 62, 62); \n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"} \n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(75, 75, 75);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(121, 121, 121)\n"
"}\n"
"")
        self.logIn_button.setObjectName("logIn_button")
        self.verticalLayout.addWidget(self.logIn_button)

        self.retranslateUi(AuthorizationForm)
        QtCore.QMetaObject.connectSlotsByName(AuthorizationForm)

    def retranslateUi(self, AuthorizationForm):
        _translate = QtCore.QCoreApplication.translate
        AuthorizationForm.setWindowTitle(_translate("AuthorizationForm", "SMTP-client By Kirill Danilchuk"))
        self.login_line.setPlaceholderText(_translate("AuthorizationForm", "Login"))
        self.password_line.setPlaceholderText(_translate("AuthorizationForm", "Password"))
        self.logIn_button.setText(_translate("AuthorizationForm", "Log in"))
from . import res_rc
