# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\view\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainForm(object):
    def setupUi(self, mainForm):
        mainForm.setObjectName("mainForm")
        mainForm.resize(681, 508)
        mainForm.setFocusPolicy(QtCore.Qt.ClickFocus)
        mainForm.setStyleSheet("QWidget {\n"
"    background-color: rgb(36, 36, 36);\n"
"    color: #FFF;\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(mainForm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.to_line = QtWidgets.QLineEdit(mainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_line.sizePolicy().hasHeightForWidth())
        self.to_line.setSizePolicy(sizePolicy)
        self.to_line.setMinimumSize(QtCore.QSize(261, 41))
        self.to_line.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.to_line.setFont(font)
        self.to_line.setStyleSheet("QLineEdit { \n"
"    border: 2px solid rgb(30, 30, 30);\n"
"    border-radius: 20px; \n"
"    color: #FFF; \n"
"    background-color: rgb(62, 62, 62); \n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"} \n"
"\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(75, 75, 75);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(102, 102, 102);\n"
"    border-color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"")
        self.to_line.setText("")
        self.to_line.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.to_line.setObjectName("to_line")
        self.verticalLayout_2.addWidget(self.to_line)
        self.subject_line = QtWidgets.QLineEdit(mainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subject_line.sizePolicy().hasHeightForWidth())
        self.subject_line.setSizePolicy(sizePolicy)
        self.subject_line.setMinimumSize(QtCore.QSize(261, 41))
        self.subject_line.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setItalic(False)
        self.subject_line.setFont(font)
        self.subject_line.setStyleSheet("QLineEdit { \n"
"    border: 2px solid rgb(30, 30, 30);\n"
"    border-radius: 20px; \n"
"    color: #FFF; \n"
"    background-color: rgb(62, 62, 62); \n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"} \n"
"\n"
"QLineEdit:hover {\n"
"    border: 3px solid rgb(75, 75, 75);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(102, 102, 102);\n"
"    border-color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"")
        self.subject_line.setText("")
        self.subject_line.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.subject_line.setObjectName("subject_line")
        self.verticalLayout_2.addWidget(self.subject_line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.message_text = QtWidgets.QTextEdit(mainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(9)
        sizePolicy.setHeightForWidth(self.message_text.sizePolicy().hasHeightForWidth())
        self.message_text.setSizePolicy(sizePolicy)
        self.message_text.setMinimumSize(QtCore.QSize(261, 41))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        font.setItalic(True)
        self.message_text.setFont(font)
        self.message_text.setStyleSheet("QTextEdit { \n"
"    border: 2px solid rgb(30, 30, 30);\n"
"    border-radius: 20px; \n"
"    color: #FFF; \n"
"    background-color: rgb(62, 62, 62); \n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"} \n"
"\n"
"QTextEdit:hover {\n"
"    border: 3px solid rgb(75, 75, 75);\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 3px solid rgb(102, 102, 102);\n"
"    border-color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"")
        self.message_text.setObjectName("message_text")
        self.horizontalLayout.addWidget(self.message_text)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.files_list = QtWidgets.QListWidget(mainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.files_list.sizePolicy().hasHeightForWidth())
        self.files_list.setSizePolicy(sizePolicy)
        self.files_list.setStyleSheet("QListWidget { \n"
"    border: 2px solid rgb(30, 30, 30);\n"
"    border-radius: 20px; \n"
"    color: #FFF; \n"
"    background-color: rgb(62, 62, 62); \n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"} \n"
"\n"
"QListWidget:hover {\n"
"    border: 3px solid rgb(75, 75, 75);\n"
"}\n"
"\n"
"QListWidgett:focus {\n"
"    border: 3px solid rgb(102, 102, 102);\n"
"    border-color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"")
        self.files_list.setObjectName("files_list")
        self.verticalLayout.addWidget(self.files_list)
        self.attach_button = QtWidgets.QPushButton(mainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.attach_button.sizePolicy().hasHeightForWidth())
        self.attach_button.setSizePolicy(sizePolicy)
        self.attach_button.setMinimumSize(QtCore.QSize(211, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.attach_button.setFont(font)
        self.attach_button.setStyleSheet("QPushButton { \n"
"    border: 2px solid rgb(30, 30, 30);\n"
"    border-radius: 20px; \n"
"    color: #FFF; \n"
"    background-color: rgb(62, 62, 62); \n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"} \n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(75, 75, 75);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(121, 121, 121)\n"
"}\n"
"")
        self.attach_button.setObjectName("attach_button")
        self.verticalLayout.addWidget(self.attach_button)
        self.clear_button = QtWidgets.QPushButton(mainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.clear_button.sizePolicy().hasHeightForWidth())
        self.clear_button.setSizePolicy(sizePolicy)
        self.clear_button.setMinimumSize(QtCore.QSize(211, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("QPushButton { \n"
"    border: 2px solid rgb(30, 30, 30);\n"
"    border-radius: 20px; \n"
"    color: #FFF; \n"
"    background-color: rgb(62, 62, 62); \n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"} \n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(75, 75, 75);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(121, 121, 121)\n"
"}\n"
"")
        self.clear_button.setObjectName("clear_button")
        self.verticalLayout.addWidget(self.clear_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.send_button = QtWidgets.QPushButton(mainForm)
        self.send_button.setMinimumSize(QtCore.QSize(211, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.send_button.setFont(font)
        self.send_button.setStyleSheet("QPushButton { \n"
"    border: 2px solid rgb(30, 30, 30);\n"
"    border-radius: 20px; \n"
"    color: #FFF; \n"
"    background-color: rgb(62, 62, 62); \n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"} \n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(0, 170, 0);\n"
"    background-color: rgb(0, 255, 0)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 170, 0);\n"
"    border: 3px solid rgb(0, 255, 0);\n"
"}\n"
"")
        self.send_button.setObjectName("send_button")
        self.horizontalLayout_2.addWidget(self.send_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.logOut_button = QtWidgets.QPushButton(mainForm)
        self.logOut_button.setMinimumSize(QtCore.QSize(211, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.logOut_button.setFont(font)
        self.logOut_button.setStyleSheet("QPushButton { \n"
"    border: 2px solid rgb(30, 30, 30);\n"
"    border-radius: 20px; \n"
"    color: #FFF; \n"
"    background-color:rgb(62, 62, 62);\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"} \n"
"\n"
"QPushButton:hover {\n"
"    border: 3px solid rgb(170,0 ,0);\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 3px solid rgb(255,0 ,0);\n"
"    background-color: rgb(170, 0, 0);\n"
"}\n"
"")
        self.logOut_button.setObjectName("logOut_button")
        self.horizontalLayout_2.addWidget(self.logOut_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(mainForm)
        QtCore.QMetaObject.connectSlotsByName(mainForm)

    def retranslateUi(self, mainForm):
        _translate = QtCore.QCoreApplication.translate
        mainForm.setWindowTitle(_translate("mainForm", "SMTP-client By Kirill Danilchuk"))
        self.to_line.setPlaceholderText(_translate("mainForm", "kirill.danilghuk01@gmail.com"))
        self.subject_line.setPlaceholderText(_translate("mainForm", "Subject:"))
        self.message_text.setPlaceholderText(_translate("mainForm", "Message"))
        self.attach_button.setText(_translate("mainForm", "Attach"))
        self.clear_button.setText(_translate("mainForm", "Clear"))
        self.send_button.setText(_translate("mainForm", "Send"))
        self.logOut_button.setText(_translate("mainForm", "Log out"))
